name: Garmin to Google Sheets Sync

on:
  schedule:
    # 04:00 UTC = 06:00 DE (Sommer) / 05:00 DE (Winter)
    # 05:00 UTC = 07:00 DE (Sommer) / 06:00 DE (Winter)
    # 10:00 UTC = 12:00 DE (Sommer) / 11:00 DE (Winter)
    # 11:00 UTC = 13:00 DE (Sommer) / 12:00 DE (Winter)
    # 18:00 UTC = 20:00 DE (Sommer) / 19:00 DE (Winter)
    # 19:00 UTC = 21:00 DE (Sommer) / 20:00 DE (Winter)
    
    - cron: '0 4,5,10,11,18,19 * * *'
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run sync script
        env:
          GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GARMIN_SESSION_BASE64: ${{ secrets.GARMIN_SESSION_BASE64 }}
        run: python sync_garmin.py
